"""a

Revision ID: 17595fde5c7
Revises: b7a719cb0d
Create Date: 2014-02-15 20:18:47.811367

"""

# revision identifiers, used by Alembic.
revision = '17595fde5c7'
down_revision = 'b7a719cb0d'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
