"""aaa

Revision ID: 1929d50f0c2
Revises: 17595fde5c7
Create Date: 2014-02-15 20:21:19.427345

"""

# revision identifiers, used by Alembic.
revision = '1929d50f0c2'
down_revision = '17595fde5c7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
