"""bbb

Revision ID: 23219590301
Revises: 2bdf74c4daa
Create Date: 2014-02-15 20:24:27.688130

"""

# revision identifiers, used by Alembic.
revision = '23219590301'
down_revision = '2bdf74c4daa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default="nextval('users_id_seq'::regclass)", nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    ### end Alembic commands ###
