"""cc

Revision ID: 330fa4d172
Revises: 320f9be4280
Create Date: 2014-02-15 20:30:03.165271

"""

# revision identifiers, used by Alembic.
revision = '330fa4d172'
down_revision = '320f9be4280'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=80), nullable=True))
    op.create_unique_constraint(None, 'users', ['password'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users')
    op.drop_column('users', 'password')
    ### end Alembic commands ###
