"""a

Revision ID: b7a719cb0d
Revises: None
Create Date: 2014-02-15 20:18:19.309053

"""

# revision identifiers, used by Alembic.
revision = 'b7a719cb0d'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
